# Generated by Django 3.1.3 on 2020-11-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_img',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthdate',
        ),
    ]
