# Generated by Django 3.1.3 on 2020-11-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20201130_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='year',
            field=models.IntegerField(default=1900),
            preserve_default=False,
        ),
    ]
